/*
 * Copyright 2021 Infosys Ltd.
 * Use of this source code is governed by GNU General Public License version 2
 * that can be found in the LICENSE file or at
 * https://opensource.org/licenses/GPL-2.0
 */

package com.infy.domain;


import javax.persistence.*;
import javax.validation.constraints.*;

import java.io.Serializable;

/**
 * A IncomingEmails.
 */
@Entity
@Table(name = "incoming_emails")
public class IncomingEmails extends AbstractAuditingEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequenceGenerator")
    @SequenceGenerator(name = "sequenceGenerator")
    private Long id;

    @Column(name = "user_id")
    private String userId;

    @Column(name = "topic_id")
    private Long topicId;

    @Column(name = "post_id")
    private Long postId;

    @Column(name = "raw")
    private String raw;

    @Column(name = "error")
    private String error;

    @Column(name = "message_id")
    private String messageId;

    @Column(name = "from_address")
    private String fromAddress;

    @Column(name = "to_addresses")
    private String toAddresses;

    @Column(name = "cc_addresses")
    private String ccAddresses;

    @Column(name = "subject")
    private String subject;

    @Column(name = "rejection_message")
    private String rejectionMessage;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated;

    @NotNull
    @Column(name = "is_bounce", nullable = false)
    private Boolean isBounce;

    @Column(name = "imap_uid_validity")
    private Integer imapUidValidity;

    @Column(name = "imap_uid")
    private Integer imapUid;

    @Column(name = "imap_sync")
    private Boolean imapSync;

    @Column(name = "imap_group_id")
    private Long imapGroupId;

    @NotNull
    @Column(name = "imap_missing", nullable = false)
    private Boolean imapMissing;

    @NotNull
    @Column(name = "created_via", nullable = false)
    private Integer createdVia;

    // jhipster-needle-entity-add-field - JHipster will add fields here
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public IncomingEmails userId(String userId) {
        this.userId = userId;
        return this;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Long getTopicId() {
        return topicId;
    }

    public IncomingEmails topicId(Long topicId) {
        this.topicId = topicId;
        return this;
    }

    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    public Long getPostId() {
        return postId;
    }

    public IncomingEmails postId(Long postId) {
        this.postId = postId;
        return this;
    }

    public void setPostId(Long postId) {
        this.postId = postId;
    }

    public String getRaw() {
        return raw;
    }

    public IncomingEmails raw(String raw) {
        this.raw = raw;
        return this;
    }

    public void setRaw(String raw) {
        this.raw = raw;
    }

    public String getError() {
        return error;
    }

    public IncomingEmails error(String error) {
        this.error = error;
        return this;
    }

    public void setError(String error) {
        this.error = error;
    }

    public String getMessageId() {
        return messageId;
    }

    public IncomingEmails messageId(String messageId) {
        this.messageId = messageId;
        return this;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getFromAddress() {
        return fromAddress;
    }

    public IncomingEmails fromAddress(String fromAddress) {
        this.fromAddress = fromAddress;
        return this;
    }

    public void setFromAddress(String fromAddress) {
        this.fromAddress = fromAddress;
    }

    public String getToAddresses() {
        return toAddresses;
    }

    public IncomingEmails toAddresses(String toAddresses) {
        this.toAddresses = toAddresses;
        return this;
    }

    public void setToAddresses(String toAddresses) {
        this.toAddresses = toAddresses;
    }

    public String getCcAddresses() {
        return ccAddresses;
    }

    public IncomingEmails ccAddresses(String ccAddresses) {
        this.ccAddresses = ccAddresses;
        return this;
    }

    public void setCcAddresses(String ccAddresses) {
        this.ccAddresses = ccAddresses;
    }

    public String getSubject() {
        return subject;
    }

    public IncomingEmails subject(String subject) {
        this.subject = subject;
        return this;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getRejectionMessage() {
        return rejectionMessage;
    }

    public IncomingEmails rejectionMessage(String rejectionMessage) {
        this.rejectionMessage = rejectionMessage;
        return this;
    }

    public void setRejectionMessage(String rejectionMessage) {
        this.rejectionMessage = rejectionMessage;
    }

    public Boolean isIsAutoGenerated() {
        return isAutoGenerated;
    }

    public IncomingEmails isAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
        return this;
    }

    public void setIsAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
    }

    public Boolean isIsBounce() {
        return isBounce;
    }

    public IncomingEmails isBounce(Boolean isBounce) {
        this.isBounce = isBounce;
        return this;
    }

    public void setIsBounce(Boolean isBounce) {
        this.isBounce = isBounce;
    }

    public Integer getImapUidValidity() {
        return imapUidValidity;
    }

    public IncomingEmails imapUidValidity(Integer imapUidValidity) {
        this.imapUidValidity = imapUidValidity;
        return this;
    }

    public void setImapUidValidity(Integer imapUidValidity) {
        this.imapUidValidity = imapUidValidity;
    }

    public Integer getImapUid() {
        return imapUid;
    }

    public IncomingEmails imapUid(Integer imapUid) {
        this.imapUid = imapUid;
        return this;
    }

    public void setImapUid(Integer imapUid) {
        this.imapUid = imapUid;
    }

    public Boolean isImapSync() {
        return imapSync;
    }

    public IncomingEmails imapSync(Boolean imapSync) {
        this.imapSync = imapSync;
        return this;
    }

    public void setImapSync(Boolean imapSync) {
        this.imapSync = imapSync;
    }

    public Long getImapGroupId() {
        return imapGroupId;
    }

    public IncomingEmails imapGroupId(Long imapGroupId) {
        this.imapGroupId = imapGroupId;
        return this;
    }

    public void setImapGroupId(Long imapGroupId) {
        this.imapGroupId = imapGroupId;
    }

    public Boolean isImapMissing() {
        return imapMissing;
    }

    public IncomingEmails imapMissing(Boolean imapMissing) {
        this.imapMissing = imapMissing;
        return this;
    }

    public void setImapMissing(Boolean imapMissing) {
        this.imapMissing = imapMissing;
    }

    public Integer getCreatedVia() {
        return createdVia;
    }

    public IncomingEmails createdVia(Integer createdVia) {
        this.createdVia = createdVia;
        return this;
    }

    public void setCreatedVia(Integer createdVia) {
        this.createdVia = createdVia;
    }
    // jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof IncomingEmails)) {
            return false;
        }
        return id != null && id.equals(((IncomingEmails) o).id);
    }

    @Override
    public int hashCode() {
        return 31;
    }

    // prettier-ignore
    @Override
    public String toString() {
        return "IncomingEmails{" +
            "id=" + getId() +
            ", userId='" + getUserId() + "'" +
            ", topicId=" + getTopicId() +
            ", postId=" + getPostId() +
            ", raw='" + getRaw() + "'" +
            ", error='" + getError() + "'" +
            ", messageId='" + getMessageId() + "'" +
            ", fromAddress='" + getFromAddress() + "'" +
            ", toAddresses='" + getToAddresses() + "'" +
            ", ccAddresses='" + getCcAddresses() + "'" +
            ", subject='" + getSubject() + "'" +
            ", rejectionMessage='" + getRejectionMessage() + "'" +
            ", isAutoGenerated='" + isIsAutoGenerated() + "'" +
            ", isBounce='" + isIsBounce() + "'" +
            ", imapUidValidity=" + getImapUidValidity() +
            ", imapUid=" + getImapUid() +
            ", imapSync='" + isImapSync() + "'" +
            ", imapGroupId=" + getImapGroupId() +
            ", imapMissing='" + isImapMissing() + "'" +
            ", createdVia=" + getCreatedVia() +
            "}";
    }
}
