/*
 * Copyright 2021 Infosys Ltd.
 * Use of this source code is governed by GNU General Public License version 2
 * that can be found in the LICENSE file or at
 * https://opensource.org/licenses/GPL-2.0
 */

/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.infy.avroschema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TextClassificationResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -735772591466563724L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextClassificationResponse\",\"namespace\":\"com.infy.avroschema\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"type\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"content\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"toxicity\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"severe_toxicity\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"obscene\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"threat\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"insult\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"identity_hate\",\"type\":[\"null\",\"double\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextClassificationResponse> ENCODER =
      new BinaryMessageEncoder<TextClassificationResponse>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextClassificationResponse> DECODER =
      new BinaryMessageDecoder<TextClassificationResponse>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TextClassificationResponse> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TextClassificationResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TextClassificationResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextClassificationResponse>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TextClassificationResponse to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TextClassificationResponse from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TextClassificationResponse instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TextClassificationResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long id;
   private java.lang.String type;
   private java.lang.String content;
   private java.lang.Double toxicity;
   private java.lang.Double severe_toxicity;
   private java.lang.Double obscene;
   private java.lang.Double threat;
   private java.lang.Double insult;
   private java.lang.Double identity_hate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextClassificationResponse() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param type The new value for type
   * @param content The new value for content
   * @param toxicity The new value for toxicity
   * @param severe_toxicity The new value for severe_toxicity
   * @param obscene The new value for obscene
   * @param threat The new value for threat
   * @param insult The new value for insult
   * @param identity_hate The new value for identity_hate
   */
  public TextClassificationResponse(java.lang.Long id, java.lang.String type, java.lang.String content, java.lang.Double toxicity, java.lang.Double severe_toxicity, java.lang.Double obscene, java.lang.Double threat, java.lang.Double insult, java.lang.Double identity_hate) {
    this.id = id;
    this.type = type;
    this.content = content;
    this.toxicity = toxicity;
    this.severe_toxicity = severe_toxicity;
    this.obscene = obscene;
    this.threat = threat;
    this.insult = insult;
    this.identity_hate = identity_hate;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return type;
    case 2: return content;
    case 3: return toxicity;
    case 4: return severe_toxicity;
    case 5: return obscene;
    case 6: return threat;
    case 7: return insult;
    case 8: return identity_hate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: type = value$ != null ? value$.toString() : null; break;
    case 2: content = value$ != null ? value$.toString() : null; break;
    case 3: toxicity = (java.lang.Double)value$; break;
    case 4: severe_toxicity = (java.lang.Double)value$; break;
    case 5: obscene = (java.lang.Double)value$; break;
    case 6: threat = (java.lang.Double)value$; break;
    case 7: insult = (java.lang.Double)value$; break;
    case 8: identity_hate = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.String getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.String value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'toxicity' field.
   * @return The value of the 'toxicity' field.
   */
  public java.lang.Double getToxicity() {
    return toxicity;
  }


  /**
   * Sets the value of the 'toxicity' field.
   * @param value the value to set.
   */
  public void setToxicity(java.lang.Double value) {
    this.toxicity = value;
  }

  /**
   * Gets the value of the 'severe_toxicity' field.
   * @return The value of the 'severe_toxicity' field.
   */
  public java.lang.Double getSevereToxicity() {
    return severe_toxicity;
  }


  /**
   * Sets the value of the 'severe_toxicity' field.
   * @param value the value to set.
   */
  public void setSevereToxicity(java.lang.Double value) {
    this.severe_toxicity = value;
  }

  /**
   * Gets the value of the 'obscene' field.
   * @return The value of the 'obscene' field.
   */
  public java.lang.Double getObscene() {
    return obscene;
  }


  /**
   * Sets the value of the 'obscene' field.
   * @param value the value to set.
   */
  public void setObscene(java.lang.Double value) {
    this.obscene = value;
  }

  /**
   * Gets the value of the 'threat' field.
   * @return The value of the 'threat' field.
   */
  public java.lang.Double getThreat() {
    return threat;
  }


  /**
   * Sets the value of the 'threat' field.
   * @param value the value to set.
   */
  public void setThreat(java.lang.Double value) {
    this.threat = value;
  }

  /**
   * Gets the value of the 'insult' field.
   * @return The value of the 'insult' field.
   */
  public java.lang.Double getInsult() {
    return insult;
  }


  /**
   * Sets the value of the 'insult' field.
   * @param value the value to set.
   */
  public void setInsult(java.lang.Double value) {
    this.insult = value;
  }

  /**
   * Gets the value of the 'identity_hate' field.
   * @return The value of the 'identity_hate' field.
   */
  public java.lang.Double getIdentityHate() {
    return identity_hate;
  }


  /**
   * Sets the value of the 'identity_hate' field.
   * @param value the value to set.
   */
  public void setIdentityHate(java.lang.Double value) {
    this.identity_hate = value;
  }

  /**
   * Creates a new TextClassificationResponse RecordBuilder.
   * @return A new TextClassificationResponse RecordBuilder
   */
  public static com.infy.avroschema.TextClassificationResponse.Builder newBuilder() {
    return new com.infy.avroschema.TextClassificationResponse.Builder();
  }

  /**
   * Creates a new TextClassificationResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextClassificationResponse RecordBuilder
   */
  public static com.infy.avroschema.TextClassificationResponse.Builder newBuilder(com.infy.avroschema.TextClassificationResponse.Builder other) {
    if (other == null) {
      return new com.infy.avroschema.TextClassificationResponse.Builder();
    } else {
      return new com.infy.avroschema.TextClassificationResponse.Builder(other);
    }
  }

  /**
   * Creates a new TextClassificationResponse RecordBuilder by copying an existing TextClassificationResponse instance.
   * @param other The existing instance to copy.
   * @return A new TextClassificationResponse RecordBuilder
   */
  public static com.infy.avroschema.TextClassificationResponse.Builder newBuilder(com.infy.avroschema.TextClassificationResponse other) {
    if (other == null) {
      return new com.infy.avroschema.TextClassificationResponse.Builder();
    } else {
      return new com.infy.avroschema.TextClassificationResponse.Builder(other);
    }
  }

  /**
   * RecordBuilder for TextClassificationResponse instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextClassificationResponse>
    implements org.apache.avro.data.RecordBuilder<TextClassificationResponse> {

    private java.lang.Long id;
    private java.lang.String type;
    private java.lang.String content;
    private java.lang.Double toxicity;
    private java.lang.Double severe_toxicity;
    private java.lang.Double obscene;
    private java.lang.Double threat;
    private java.lang.Double insult;
    private java.lang.Double identity_hate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.infy.avroschema.TextClassificationResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.content)) {
        this.content = data().deepCopy(fields()[2].schema(), other.content);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.toxicity)) {
        this.toxicity = data().deepCopy(fields()[3].schema(), other.toxicity);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.severe_toxicity)) {
        this.severe_toxicity = data().deepCopy(fields()[4].schema(), other.severe_toxicity);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.obscene)) {
        this.obscene = data().deepCopy(fields()[5].schema(), other.obscene);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.threat)) {
        this.threat = data().deepCopy(fields()[6].schema(), other.threat);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.insult)) {
        this.insult = data().deepCopy(fields()[7].schema(), other.insult);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.identity_hate)) {
        this.identity_hate = data().deepCopy(fields()[8].schema(), other.identity_hate);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing TextClassificationResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(com.infy.avroschema.TextClassificationResponse other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.content)) {
        this.content = data().deepCopy(fields()[2].schema(), other.content);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.toxicity)) {
        this.toxicity = data().deepCopy(fields()[3].schema(), other.toxicity);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.severe_toxicity)) {
        this.severe_toxicity = data().deepCopy(fields()[4].schema(), other.severe_toxicity);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.obscene)) {
        this.obscene = data().deepCopy(fields()[5].schema(), other.obscene);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.threat)) {
        this.threat = data().deepCopy(fields()[6].schema(), other.threat);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.insult)) {
        this.insult = data().deepCopy(fields()[7].schema(), other.insult);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.identity_hate)) {
        this.identity_hate = data().deepCopy(fields()[8].schema(), other.identity_hate);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder setId(java.lang.Long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.String getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder setType(java.lang.String value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.String getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder setContent(java.lang.String value) {
      validate(fields()[2], value);
      this.content = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder clearContent() {
      content = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'toxicity' field.
      * @return The value.
      */
    public java.lang.Double getToxicity() {
      return toxicity;
    }


    /**
      * Sets the value of the 'toxicity' field.
      * @param value The value of 'toxicity'.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder setToxicity(java.lang.Double value) {
      validate(fields()[3], value);
      this.toxicity = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'toxicity' field has been set.
      * @return True if the 'toxicity' field has been set, false otherwise.
      */
    public boolean hasToxicity() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'toxicity' field.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder clearToxicity() {
      toxicity = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'severe_toxicity' field.
      * @return The value.
      */
    public java.lang.Double getSevereToxicity() {
      return severe_toxicity;
    }


    /**
      * Sets the value of the 'severe_toxicity' field.
      * @param value The value of 'severe_toxicity'.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder setSevereToxicity(java.lang.Double value) {
      validate(fields()[4], value);
      this.severe_toxicity = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'severe_toxicity' field has been set.
      * @return True if the 'severe_toxicity' field has been set, false otherwise.
      */
    public boolean hasSevereToxicity() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'severe_toxicity' field.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder clearSevereToxicity() {
      severe_toxicity = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'obscene' field.
      * @return The value.
      */
    public java.lang.Double getObscene() {
      return obscene;
    }


    /**
      * Sets the value of the 'obscene' field.
      * @param value The value of 'obscene'.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder setObscene(java.lang.Double value) {
      validate(fields()[5], value);
      this.obscene = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'obscene' field has been set.
      * @return True if the 'obscene' field has been set, false otherwise.
      */
    public boolean hasObscene() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'obscene' field.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder clearObscene() {
      obscene = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'threat' field.
      * @return The value.
      */
    public java.lang.Double getThreat() {
      return threat;
    }


    /**
      * Sets the value of the 'threat' field.
      * @param value The value of 'threat'.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder setThreat(java.lang.Double value) {
      validate(fields()[6], value);
      this.threat = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'threat' field has been set.
      * @return True if the 'threat' field has been set, false otherwise.
      */
    public boolean hasThreat() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'threat' field.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder clearThreat() {
      threat = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'insult' field.
      * @return The value.
      */
    public java.lang.Double getInsult() {
      return insult;
    }


    /**
      * Sets the value of the 'insult' field.
      * @param value The value of 'insult'.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder setInsult(java.lang.Double value) {
      validate(fields()[7], value);
      this.insult = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'insult' field has been set.
      * @return True if the 'insult' field has been set, false otherwise.
      */
    public boolean hasInsult() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'insult' field.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder clearInsult() {
      insult = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'identity_hate' field.
      * @return The value.
      */
    public java.lang.Double getIdentityHate() {
      return identity_hate;
    }


    /**
      * Sets the value of the 'identity_hate' field.
      * @param value The value of 'identity_hate'.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder setIdentityHate(java.lang.Double value) {
      validate(fields()[8], value);
      this.identity_hate = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'identity_hate' field has been set.
      * @return True if the 'identity_hate' field has been set, false otherwise.
      */
    public boolean hasIdentityHate() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'identity_hate' field.
      * @return This builder.
      */
    public com.infy.avroschema.TextClassificationResponse.Builder clearIdentityHate() {
      identity_hate = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextClassificationResponse build() {
      try {
        TextClassificationResponse record = new TextClassificationResponse();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.String) defaultValue(fields()[1]);
        record.content = fieldSetFlags()[2] ? this.content : (java.lang.String) defaultValue(fields()[2]);
        record.toxicity = fieldSetFlags()[3] ? this.toxicity : (java.lang.Double) defaultValue(fields()[3]);
        record.severe_toxicity = fieldSetFlags()[4] ? this.severe_toxicity : (java.lang.Double) defaultValue(fields()[4]);
        record.obscene = fieldSetFlags()[5] ? this.obscene : (java.lang.Double) defaultValue(fields()[5]);
        record.threat = fieldSetFlags()[6] ? this.threat : (java.lang.Double) defaultValue(fields()[6]);
        record.insult = fieldSetFlags()[7] ? this.insult : (java.lang.Double) defaultValue(fields()[7]);
        record.identity_hate = fieldSetFlags()[8] ? this.identity_hate : (java.lang.Double) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextClassificationResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextClassificationResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextClassificationResponse>
    READER$ = (org.apache.avro.io.DatumReader<TextClassificationResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id);
    }

    if (this.type == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.type);
    }

    if (this.content == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.content);
    }

    if (this.toxicity == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.toxicity);
    }

    if (this.severe_toxicity == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.severe_toxicity);
    }

    if (this.obscene == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.obscene);
    }

    if (this.threat == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.threat);
    }

    if (this.insult == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.insult);
    }

    if (this.identity_hate == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.identity_hate);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.type = null;
      } else {
        this.type = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.content = null;
      } else {
        this.content = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.toxicity = null;
      } else {
        this.toxicity = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.severe_toxicity = null;
      } else {
        this.severe_toxicity = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.obscene = null;
      } else {
        this.obscene = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.threat = null;
      } else {
        this.threat = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.insult = null;
      } else {
        this.insult = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.identity_hate = null;
      } else {
        this.identity_hate = in.readDouble();
      }

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.type = null;
          } else {
            this.type = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.content = null;
          } else {
            this.content = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.toxicity = null;
          } else {
            this.toxicity = in.readDouble();
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.severe_toxicity = null;
          } else {
            this.severe_toxicity = in.readDouble();
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.obscene = null;
          } else {
            this.obscene = in.readDouble();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.threat = null;
          } else {
            this.threat = in.readDouble();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.insult = null;
          } else {
            this.insult = in.readDouble();
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.identity_hate = null;
          } else {
            this.identity_hate = in.readDouble();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










