import { TestBed, getTestBed } from '@angular/core/testing';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import { IncomingEmailsService } from 'app/entities/incoming-emails/incoming-emails.service';
import { IIncomingEmails, IncomingEmails } from 'app/shared/model/incoming-emails.model';

describe('Service Tests', () => {
  describe('IncomingEmails Service', () => {
    let injector: TestBed;
    let service: IncomingEmailsService;
    let httpMock: HttpTestingController;
    let elemDefault: IIncomingEmails;
    let expectedResult: IIncomingEmails | IIncomingEmails[] | boolean | null;

    beforeEach(() => {
      TestBed.configureTestingModule({
        imports: [HttpClientTestingModule],
      });
      expectedResult = null;
      injector = getTestBed();
      service = injector.get(IncomingEmailsService);
      httpMock = injector.get(HttpTestingController);

      elemDefault = new IncomingEmails(
        0,
        'AAAAAAA',
        0,
        0,
        'AAAAAAA',
        'AAAAAAA',
        'AAAAAAA',
        'AAAAAAA',
        'AAAAAAA',
        'AAAAAAA',
        'AAAAAAA',
        'AAAAAAA',
        false,
        false,
        0,
        0,
        false,
        0,
        false,
        0
      );
    });

    describe('Service methods', () => {
      it('should find an element', () => {
        const returnedFromService = Object.assign({}, elemDefault);

        service.find(123).subscribe(resp => (expectedResult = resp.body));

        const req = httpMock.expectOne({ method: 'GET' });
        req.flush(returnedFromService);
        expect(expectedResult).toMatchObject(elemDefault);
      });

      it('should create a IncomingEmails', () => {
        const returnedFromService = Object.assign(
          {
            id: 0,
          },
          elemDefault
        );

        const expected = Object.assign({}, returnedFromService);

        service.create(new IncomingEmails()).subscribe(resp => (expectedResult = resp.body));

        const req = httpMock.expectOne({ method: 'POST' });
        req.flush(returnedFromService);
        expect(expectedResult).toMatchObject(expected);
      });

      it('should update a IncomingEmails', () => {
        const returnedFromService = Object.assign(
          {
            userId: 'BBBBBB',
            topicId: 1,
            postId: 1,
            raw: 'BBBBBB',
            error: 'BBBBBB',
            messageId: 'BBBBBB',
            fromAddress: 'BBBBBB',
            toAddresses: 'BBBBBB',
            ccAddresses: 'BBBBBB',
            subject: 'BBBBBB',
            rejectionMessage: 'BBBBBB',
            isAutoGenerated: true,
            isBounce: true,
            imapUidValidity: 1,
            imapUid: 1,
            imapSync: true,
            imapGroupId: 1,
            imapMissing: true,
            createdVia: 1,
          },
          elemDefault
        );

        const expected = Object.assign({}, returnedFromService);

        service.update(expected).subscribe(resp => (expectedResult = resp.body));

        const req = httpMock.expectOne({ method: 'PUT' });
        req.flush(returnedFromService);
        expect(expectedResult).toMatchObject(expected);
      });

      it('should return a list of IncomingEmails', () => {
        const returnedFromService = Object.assign(
          {
            userId: 'BBBBBB',
            topicId: 1,
            postId: 1,
            raw: 'BBBBBB',
            error: 'BBBBBB',
            messageId: 'BBBBBB',
            fromAddress: 'BBBBBB',
            toAddresses: 'BBBBBB',
            ccAddresses: 'BBBBBB',
            subject: 'BBBBBB',
            rejectionMessage: 'BBBBBB',
            isAutoGenerated: true,
            isBounce: true,
            imapUidValidity: 1,
            imapUid: 1,
            imapSync: true,
            imapGroupId: 1,
            imapMissing: true,
            createdVia: 1,
          },
          elemDefault
        );

        const expected = Object.assign({}, returnedFromService);

        service.query().subscribe(resp => (expectedResult = resp.body));

        const req = httpMock.expectOne({ method: 'GET' });
        req.flush([returnedFromService]);
        httpMock.verify();
        expect(expectedResult).toContainEqual(expected);
      });

      it('should delete a IncomingEmails', () => {
        service.delete(123).subscribe(resp => (expectedResult = resp.ok));

        const req = httpMock.expectOne({ method: 'DELETE' });
        req.flush({ status: 200 });
        expect(expectedResult);
      });
    });

    afterEach(() => {
      httpMock.verify();
    });
  });
});
